package photoclient.lazada.com.photoclient.utility;

/**
 * Define all the Constants used over the app.
 * Created by avi_chopra on 15/06/16.
 */
public class Constants {
    public static final String BASE_URL = "https://api.500px.com/";
    public static final int TIMEOUT = 15;

    //Consumer key generated by Signing up
    public static final String consumer_key_name = "consumer_key";
    public static final String consumer_key_value = "xLJ3H4dscGs3xTiA3yNlpFV6Vt7CMxlxRpVVBVHo";

    public static final String feature_key_name = "feature";
    public static final String feature_key_value = "popular";

    //Categories supported from https://github.com/500px/api-documentation/blob/master/basics/formats_and_terms.md
    public static final String[] categoriesList = {
            "Uncategorized",
            "Abstract",
            "Animals",
            "Black and White",
            "Celebrities",
            "City and Architecture",
            "Commercial",
            "Concert",
            "Family",
            "Fashion",
            "Film",
            "Fine Art",
            "Food",
            "Journalism",
            "Landscapes",
            "Macro",
            "Nature",
            "Nude",
            "People",
            "Performing Arts",
            "Sport",
            "Still Life",
            "Street",
            "Transportation",
            "Travel",
            "Underwater",
            "Urban Exploration",
            "Wedding"
    };


    public static final String CategoryName = "CATEGORY";
    public static final String PHOTO = "PHOTO";
}
